Repository Diegogagan2587/A-Dedo, pull requests merged in 2024-06, with the labels that each got.

#5 Backend/authentication
  backend/package.json
  backend/src/controllers/usersController.js
  backend/src/db/connection.js
  backend/src/models/trip.js
  backend/src/models/user.js
  backend/src/models/vehicle.js
  backend/src/router/routes.js
  backend/src/server.js
  backend/src/user-registration-api/app.js
Labels: enhancement

#8 Feat/front install redux
  frontend/package-lock.json
  frontend/package.json
  frontend/src/config.js
  frontend/src/main.jsx
  frontend/src/store/slices/userSlice.js
  frontend/src/store/store.js
Labels: enhancement

#9 Feat/front authentication
  frontend/src/components/Input.jsx
  frontend/src/pages/Login.jsx
  frontend/src/store/requests/authenticateUser.js
  frontend/src/store/slices/userSlice.js
Labels: enhancement

#15 CORS
  backend/package.json
  backend/src/server.js
Labels: enhancement

#17 Backend/trip
  backend/src/controllers/tripsController.js
  backend/src/controllers/usersController.js
  backend/src/router/routes.js
Labels: enhancement

#21 Back End: Update trip model and controller
  backend/src/controllers/tripsController.js
  backend/src/models/trip.js
Labels: enhancement

#23 Back End: Fix trips controller
  backend/src/controllers/tripsController.js
Labels: bug

#20 Front-End: create and Post a Trip
  frontend/src/components/BtnNextIcon.jsx
  frontend/src/components/PopupCreateTrip.jsx
  frontend/src/pages/trips/new/CreateTripPartFour.jsx
  frontend/src/pages/trips/new/CreateTripPartOne.jsx
  frontend/src/pages/trips/new/CreateTripPartThree.jsx
  frontend/src/pages/trips/new/CreateTripPartTwo.jsx
  frontend/src/store/requests/createTrip.js
  frontend/src/store/slices/tripsSlice.js
  frontend/src/store/store.js
Labels: enhancement

#24 Front End: Verticall animation on Navigation
  frontend/src/App.jsx
  frontend/src/components/navbar/Menu.jsx
  frontend/src/components/navbar/Navbar.jsx
Labels: enhancement

#28 Create Account
  frontend/src/components/PopupCreateAccount.jsx
  frontend/src/components/navbar/Item.jsx
  frontend/src/components/navbar/Menu.jsx
  frontend/src/components/navbar/Navbar.jsx
  frontend/src/pages/register/user/CreateAccountOne.jsx
  frontend/src/pages/register/user/CreateAccountTwo.jsx
  frontend/src/store/requests/registerUser.js
  frontend/src/store/slices/userSlice.js
Labels: enhancement

#29 Back End: Update User
  backend/src/controllers/usersController.js
  backend/src/models/user.js
Labels: enhancement

#32 Feat/front/renders and api connection
  frontend/src/App.jsx
  frontend/src/components/CardTrip.jsx
  frontend/src/components/PopupReserveTrip.jsx
  frontend/src/components/Switch.jsx
  frontend/src/components/navbar/Menu.jsx
  frontend/src/components/navbar/Navbar.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/trips/ReserveTrip.jsx
  frontend/src/pages/trips/TripDetails.jsx
  frontend/src/store/requests/authenticateUser.js
  frontend/src/store/requests/getTrips.js
  frontend/src/store/requests/logoutUser.js
  frontend/src/store/requests/postReservation.js
  frontend/src/store/requests/registerDriver.js
  frontend/src/store/requests/reserveTrip.js
  frontend/src/store/slices/tripsSlice.js
  frontend/src/store/slices/userSlice.js
  frontend/src/store/utils/sortTripsByDate.js
Labels: bug

#37 Front End: Fix Navigation Overllaping
  frontend/src/App.jsx
  frontend/src/pages/trips/ReserveTrip.jsx
  frontend/src/pages/trips/TripDetails.jsx
Labels: bug

#48 Front End: Testing Set Up
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.test.jsx
  frontend/src/components/navbar/Navbar.jsx
  frontend/tests/Example.test.jsx
  frontend/tests/setup.js
  frontend/vite.config.js
Labels: enhancement

#52 Fix/front/fonts
  frontend/index.html
  frontend/src/pages/Main.jsx
  frontend/tailwind.config.js
Labels: bug, enhancement

#53 fix/front/PassenderDriverBtn.jsx (switch)
  frontend/src/components/PassengerDriverBtn.jsx
Labels: bug

#54 Front End: Fix Date for components that render from Global Storage
  frontend/src/components/CardDriverTrip.jsx
  frontend/src/components/DateDisplay.jsx
  frontend/src/pages/Home.jsx
Labels: bug, enhancement

#56 Fix/front/drivers trip details no navigation
  frontend/src/components/navbar/Navbar.jsx
  frontend/src/pages/profile-driver/DriverDetailTrip.jsx
  frontend/src/pages/profile-driver/NavDetailsTrip.jsx
Labels: bug

#57 Fix/card trip profile placeholder
  frontend/src/components/CardTrip.jsx
  frontend/src/pages/Home.jsx
Labels: bug, enhancement

#60 Front End: Home Page updates && related accesibility issues
  Readme.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/GreenButton.jsx
  frontend/src/components/Input.jsx
  frontend/src/components/PassengerDriverBtn.jsx
  frontend/src/components/PopupCreateAccount.jsx
  frontend/src/components/RegisterBtn.jsx
  frontend/src/components/buttons/GreenLinkButton.jsx
  frontend/src/components/navbar/Menu.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/LandingPage.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/register/driver/CarRegister.jsx
  frontend/src/pages/register/driver/DriverRegister.jsx
  frontend/src/pages/register/driver/DriverRegistrationSuccess.jsx
  frontend/src/pages/register/driver/VehicleRegistrationSuccess.jsx
  frontend/src/pages/register/user/PasswordAndTermsForm.jsx
  frontend/src/pages/register/user/UserDetailsForm.jsx
  frontend/src/pages/register/user/UserRegistrationSuccess.jsx
  frontend/src/pages/trips/TripReservationSuccess.jsx
  frontend/src/pages/trips/new/TripCreationSuccess.jsx
  frontend/src/store/request/reserveTrip.js
  frontend/src/store/slices/userSlice.js
  frontend/tests/integration/DriverRegisterFlow.test.jsx
  frontend/tests/integration/SignUpFlow.test.jsx
  frontend/tests/integration/exampleTrips.js
Labels: bug, enhancement
